// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZTDB.SQLDatabase;

namespace ZTDB.SQLDatabase.Migrations
{
    [DbContext(typeof(SQLContext))]
    [Migration("20191214192350_SomeImprovment")]
    partial class SomeImprovment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZTDB.SQLDatabase.Models.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("ZTDB.SQLDatabase.Models.CancelCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CancelCode");
                });

            modelBuilder.Entity("ZTDB.SQLDatabase.Models.DataToImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ACTUAL_ELAPSED_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AIR_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARR_DELAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARR_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CANCELLATION_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CANCELLED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CARRIER_DELAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CRS_ARR_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CRS_DEP_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CRS_ELAPSED_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEP_DELAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEP_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISTANCE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIVERTED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FL_DATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LATE_AIRCRAFT_DELAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAS_DELAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OP_CARRIER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OP_CARRIER_FL_NUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ORIGIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECURITY_DELAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TAXI_IN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TAXI_OUT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WEATHER_DELAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WHEELS_OFF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WHEELS_ON")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataToImport");
                });

            modelBuilder.Entity("ZTDB.SQLDatabase.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ActualArrivalTime")
                        .HasColumnType("Numeric(18,2)");

                    b.Property<decimal>("ActualDepartureTime")
                        .HasColumnType("Numeric(18,2)");

                    b.Property<decimal>("ActualElapsedTime")
                        .HasColumnType("Numeric(18,2)");

                    b.Property<decimal>("AirTime")
                        .HasColumnType("Numeric(18,2)");

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<decimal>("ArrivalDelay")
                        .HasColumnType("Numeric(18,2)");

                    b.Property<int?>("CancelCodeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CarrierDelay")
                        .HasColumnType("Numeric(18,2)");

                    b.Property<decimal>("DepartureDelay")
                        .HasColumnType("Numeric(18,2)");

                    b.Property<int?>("DestinationLocationId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<decimal>("Distance")
                        .HasColumnType("Numeric(18,2)");

                    b.Property<decimal>("Diverted")
                        .HasColumnType("Numeric(18,2)");

                    b.Property<DateTime>("FlightDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LateAircraftDelay")
                        .HasColumnType("Numeric(18,2)");

                    b.Property<decimal?>("NasDelay")
                        .HasColumnType("Numeric(18,2)");

                    b.Property<int>("OpCarrierFlightNumber")
                        .HasColumnType("int");

                    b.Property<int?>("OriginLocationId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<decimal>("PlannedArrivalTime")
                        .HasColumnType("Numeric(18,2)");

                    b.Property<decimal>("PlannedDepartureTime")
                        .HasColumnType("Numeric(18,2)");

                    b.Property<decimal>("PlannedElapsedTime")
                        .HasColumnType("Numeric(18,2)");

                    b.Property<decimal?>("SecurityDelay")
                        .HasColumnType("Numeric(18,2)");

                    b.Property<decimal>("TaxiIn")
                        .HasColumnType("Numeric(18,2)");

                    b.Property<decimal>("TaxiOut")
                        .HasColumnType("Numeric(18,2)");

                    b.Property<decimal?>("WeatherDelay")
                        .HasColumnType("Numeric(18,2)");

                    b.Property<decimal>("WheelsOff")
                        .HasColumnType("Numeric(18,2)");

                    b.Property<decimal>("WheelsOn")
                        .HasColumnType("Numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("CancelCodeId");

                    b.HasIndex("DestinationLocationId");

                    b.HasIndex("OriginLocationId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("ZTDB.SQLDatabase.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ZTDB.SQLDatabase.Models.Flight", b =>
                {
                    b.HasOne("ZTDB.SQLDatabase.Models.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZTDB.SQLDatabase.Models.CancelCode", "CancelCode")
                        .WithMany("Flights")
                        .HasForeignKey("CancelCodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ZTDB.SQLDatabase.Models.Location", "DestinationLocation")
                        .WithMany("DestinationFlights")
                        .HasForeignKey("DestinationLocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ZTDB.SQLDatabase.Models.Location", "OriginLocation")
                        .WithMany("OriginFlights")
                        .HasForeignKey("OriginLocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
