// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZTDB.SQLDatabase;

namespace ZTDB.SQLDatabase.Migrations
{
    [DbContext(typeof(SQLContext))]
    partial class SQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZTDB.SQLDatabase.Models.DataToImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ACTUAL_ELAPSED_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AIR_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARR_DELAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARR_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CANCELLATION_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CANCELLED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CARRIER_DELAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CRS_ARR_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CRS_DEP_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CRS_ELAPSED_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEP_DELAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEP_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISTANCE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIVERTED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FL_DATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LATE_AIRCRAFT_DELAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAS_DELAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OP_CARRIER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OP_CARRIER_FL_NUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ORIGIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECURITY_DELAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TAXI_IN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TAXI_OUT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WEATHER_DELAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WHEELS_OFF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WHEELS_ON")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataToImport");
                });
#pragma warning restore 612, 618
        }
    }
}
